/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.vista;

import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 * Esta clase es la visualizacion de los componentes de añadir un registro a la base de datos
 * @author raul
 */
public class AnnadirLibro extends javax.swing.JPanel {

    /**
     * Constructor de la clase
     */
    public AnnadirLibro() {
        initComponents();
    }
    
    /**
     * Es un método que añade el control a los botones
     * @param l Es el controlador de tipo ActionListener
     */
    public void addControlador(ActionListener l){
        buscar.setActionCommand("buscar");
        buscar.addActionListener(l);
        aceptar.setActionCommand("aceptar");
        aceptar.addActionListener(l);
        cancelar.setActionCommand("cancelar");
        cancelar.addActionListener(l);
    }
    
    /**
     * Se encarga de cambiar poner la ubicación de la imagen
     * @param str Es el path de la imagen.
     */
    public void setUrlImagen(String str){
        urlImg.setText(str);
    }
    
    /**
     * Se encarga de cambiar la imagen de la pantalla
     * @param str Es el path de la imagen
     */
    public void setImagen(String str){
        ImageIcon img=new ImageIcon(str);
        ImageIcon imgScale=new ImageIcon(img.getImage().getScaledInstance(150, 240, Image.SCALE_DEFAULT));
        
        imagen.setIcon(imgScale);
    }
    
    /**
     * Obtiene el valor del campo Nombre
     * @return Devuelve un String que esta contenido en el campo Nombre
     */
    public String getNombre(){
        return nombre.getText();
    }
    
    /**
     * Obtiene el valor del campo Autor
     * @return Devuelve un String que esta contenido en el campo Autor
     */
    public String getAutor(){
        return autor.getText();
    }
    
    /**
     * Obtiene el valor del campo Año
     * @return Devuelve un String que esta contenido en el campo Año
     */
    public String getAnno(){
        return anno.getText();
    }
    
    /**
     * Obtiene el valor del campo Argumento
     * @return Devuelve un String que esta contenido en el campo Argumento
     */
    public String getArgumento(){
        return argumento.getText();
    }
    
    /**
     * Obtiene el valor del campo Genero
     * @return Devuelve un String que esta contenido en el campo Genero
     */
    public String getGenero(){
        return genero.getText();
    }
    
    /**
     * Obtiene el valor del campo Imagen
     * @return Devuelve un String que esta contenido en el campo Imagen
     */
    public String getImagen(){
        return urlImg.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        anno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        urlImg = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        argumento = new javax.swing.JTextArea();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectofinal/img/imagen.jpg"))); // NOI18N

        jLabel2.setText("Nombre: ");

        jLabel3.setText("Autor:");

        jLabel4.setText("Año: ");

        jLabel5.setText("Genero: ");

        buscar.setText("...");
        buscar.setToolTipText("Buscar");

        jLabel6.setText("Portada: ");

        jLabel7.setText("Argumento: ");

        argumento.setColumns(20);
        argumento.setRows(5);
        jScrollPane1.setViewportView(argumento);

        aceptar.setText("Aceptar");

        cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(autor)
                            .addComponent(anno)
                            .addComponent(genero)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(urlImg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField anno;
    private javax.swing.JTextArea argumento;
    private javax.swing.JTextField autor;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField genero;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField urlImg;
    // End of variables declaration//GEN-END:variables
}
