/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal.vista;

import java.awt.Image;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;

/**
 * Clase que visualiza los detalles de los registros de la base de datos
 * @author raul
 */

public class PrevisualizarLibro extends JPanel {
    
    private JTextField anno;
    private JTextArea argumento;
    private JTextField autor;
    private JTextField genero;
    private JLabel imagen;
    private JButton butAceptar;
    private JLabel lblNombre;
    private JLabel lblAutor;
    private JLabel lblAnno;
    private JLabel lblGenero;
    private JLabel lblArgumento;
    private JScrollPane jScrollPane1;
    private JTextField nombre;
    
    /**
     * Constructor de la clase
     */
    public PrevisualizarLibro(){

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        imagen = new JLabel();
        lblNombre = new JLabel();
        nombre = new JTextField();
        lblAutor = new JLabel();
        autor = new JTextField();
        lblAnno = new JLabel();
        anno = new JTextField();
        lblGenero = new JLabel();
        genero = new JTextField();
        lblArgumento = new JLabel();
        jScrollPane1 = new JScrollPane();
        argumento = new JTextArea();
        butAceptar = new JButton();

        imagen.setIcon(new ImageIcon(getClass().getResource("/proyectofinal/img/imagen.jpg"))); 

        lblNombre.setText("Nombre:");

        lblAutor.setText("Autor:");

        lblAnno.setText("Año de publicaión:");

        lblGenero.setText("Género:");

        lblArgumento.setText("Argumento:");

        argumento.setColumns(20);
        argumento.setRows(5);
        argumento.setWrapStyleWord(true);
        argumento.setLineWrap(true);
        jScrollPane1.setViewportView(argumento);
        
        nombre.setEditable(false);
        autor.setEditable(false);
        anno.setEditable(false);
        genero.setEditable(false);
        argumento.setEditable(false);

        butAceptar.setText("Aceptar");

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(imagen, GroupLayout.PREFERRED_SIZE, 152, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(genero, GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblAutor)
                                    .addComponent(lblAnno)
                                    .addComponent(lblGenero))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(anno)
                            .addComponent(autor)
                            .addComponent(nombre)))
                    .addComponent(lblArgumento)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagen, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAutor)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(autor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAnno)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anno, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGenero)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genero, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblArgumento)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 158, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butAceptar)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }                      
                                  
    
    /**
     * Es el metodo encargado de introducir los valores en la pantalla
     * @param obj Es el registro recibido de la base de dato (0 - Nombre, 1 - Autor, 2 - Año, 3 - Genero, 4 - Argumento, 5 - Imagen)
     */
    public void cargarDatos(Object[] obj){
        String url;
        setNombre(obj[0].toString());
        if(obj[1]!=null){
            setAutor(obj[1].toString());
        }
        if(obj[2]!=null){
            setAnno(obj[2].toString());
        }
        if(obj[3]!=null){
            setGenero(obj[3].toString());
        }
        if(obj[4]!=null){
            setArgumento(obj[4].toString());
        }
        
        if(obj[5]==null){
            url="../img/imagen.jpg";
        }
        else{
            url=obj[5].toString();
        }
        setImagen(url);
    }
    
    /**
     * Se encarga de cambiar la imagen
     * @param str Es la dirección de la imagen
     */
    public void setImagen(String str){
        ImageIcon img=new ImageIcon(this.getClass().getResource(str));
        ImageIcon imgScale=new ImageIcon(img.getImage().getScaledInstance(150, 240, Image.SCALE_DEFAULT));
        
        imagen.setIcon(imgScale);
    }
    
    /**
     * Se encarga de cambiar el nombre
     * @param str Es el nombre
     */
    public void setNombre(String str){
        nombre.setText(str);
    }
    
    /**
     * Se encarga de cambiar el autor
     * @param str Es el autor
     */
    public void setAutor(String str){
        autor.setText(str);
    }
    
    /**
     * Se encarga de cambiar el año
     * @param str Es el año
     */
    public void setAnno(String str){
        anno.setText(str);
    }
    
    /**
     * Se encarga de cambiar el argumentp
     * @param str Es el argumento
     */
    public void setArgumento(String str){
        argumento.setText(str);
    }

    /**
     * Se encarga de cambiar el genero
     * @param str Es el genero
     */
    private void setGenero(String str) {
        genero.setText(str);
    }
}
